"""frame — the half of the app that the delivery system depends on. Do not edit this file.

An app built on Basis gets rewritten; this does not. It holds the three endpoints every launcher relies on,
the page, the static files, and the data folder:

    /health         is it up. The launcher waits for this before opening a browser.
    /api/ping       the heartbeat. When it stops, the app stops — which is what makes "close the window"
                    mean "push the data" on a laptop and on the phone alike.
    /api/quit       stop now.
    /api/state      what the shell page reports.
    /api/sync/pull  ·  /api/sync/push

Add routes in `app.py`, never here:

    import frame

    @frame.route("GET", "/api/sprites")
    def sprites(request):
        return {"sprites": [...]}                  # a dict or list is sent as JSON

    @frame.route("POST", "/api/sprites")
    def add(request):
        name = (request.json.get("name") or "").strip()
        if not name:
            return 400, {"error": "a name is needed"}
        ...

A handler is given a Request and returns a dict or list (JSON), a (status, dict) pair, `frame.html(text)`,
or `frame.raw(bytes, content_type)`. Registering "GET" "/" replaces the shell page.

Everything the app keeps goes under `frame.DATA` — the folder a launcher points it at, outside the code, so
an update never touches it and the sync knows what to carry.
"""
from __future__ import annotations

import json
import os
import threading
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import datasync

ROOT = os.path.dirname(os.path.abspath(__file__))
INFO = json.load(open(os.path.join(ROOT, "appinfo.json"), encoding="utf-8"))
DATA = datasync.DATA
IDLE = int(os.environ.get("APP_IDLE_SECONDS", "120"))
STARTED = time.time()

ROUTES: dict = {}
PAGE_TOKENS: dict = {}                              # extra {{token}} values for index.html
TYPES = {".css": "text/css", ".js": "text/javascript", ".svg": "image/svg+xml", ".png": "image/png",
         ".jpg": "image/jpeg", ".webp": "image/webp", ".ico": "image/x-icon", ".json": "application/json",
         ".woff2": "font/woff2", ".map": "application/json"}


# --------------------------------------------------------------------------------- what a handler is given
class Request:
    def __init__(self, method: str, path: str, query: str, body: bytes):
        self.method, self.path, self.body = method, path, body
        self.query = {k: v[0] for k, v in urllib.parse.parse_qs(query).items()}

    @property
    def json(self) -> dict:
        try:
            parsed = json.loads(self.body or b"{}")
            return parsed if isinstance(parsed, dict) else {"value": parsed}
        except ValueError:
            return {}


class Raw:
    def __init__(self, body: bytes, content_type: str, status: int = 200):
        self.body, self.content_type, self.status = body, content_type, status


def html(text: str, status: int = 200) -> Raw:
    return Raw(text.encode("utf-8"), "text/html; charset=utf-8", status)


def raw(body: bytes, content_type: str = "application/octet-stream", status: int = 200) -> Raw:
    return Raw(body, content_type, status)


def route(method: str, path: str):
    def keep(fn):
        ROUTES[(method.upper(), path)] = fn
        return fn
    return keep


# --------------------------------------------------------------------------------- what the app is
def version() -> str:
    try:
        with open(os.path.join(ROOT, "VERSION"), encoding="utf-8") as f:
            return f.read().strip()
    except OSError:
        return "v0"


def port() -> int:
    return int(os.environ.get("APP_PORT") or INFO.get("port") or 5000)


def transport() -> str:
    """How this copy of the code arrived: whichever launcher started it says so."""
    return os.environ.get("APP_TRANSPORT") or "direct"


def devices() -> dict:
    try:
        with open(os.path.join(DATA, "devices.json"), encoding="utf-8") as f:
            seen = json.load(f)
            return seen if isinstance(seen, dict) else {}
    except (OSError, ValueError):
        return {}


def register() -> dict:
    """Write this device into the shared data folder on every start. It is what proves the round trip:
    run the app anywhere, and every other device sees that it ran."""
    seen = devices()
    seen[datasync.device()] = {"transport": transport(), "version": version(), "at": datasync.now(),
                               "system": os.name}
    tmp = os.path.join(DATA, "devices.json.tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        json.dump(seen, f, indent=1, sort_keys=True)
    os.replace(tmp, os.path.join(DATA, "devices.json"))
    return seen


def state() -> dict:
    return {"name": INFO["name"], "version": version(), "transport": transport(), "device": datasync.device(),
            "port": port(), "data": DATA, "repo": datasync.repo(), "linked": bool(datasync.token()),
            "uptime": int(time.time() - STARTED), "devices": devices()}


def page() -> Raw:
    with open(os.path.join(ROOT, "templates", "index.html"), encoding="utf-8") as f:
        text = f.read()
    for token, value in {"{{name}}": INFO["name"], "{{version}}": version(), **PAGE_TOKENS}.items():
        text = text.replace(token, str(value))
    return html(text)


# --------------------------------------------------------------------------------- the endpoints that stay
@route("GET", "/")
def _index(request):
    return page()


@route("GET", "/health")
@route("GET", "/api/ping")
def _ping(request):
    return {"ok": True}


@route("GET", "/api/state")
def _state(request):
    return state()


@route("GET", "/api/sync/status")
def _sync_status(request):
    return datasync.status()


@route("POST", "/api/sync/pull")
def _sync_pull(request):
    return datasync.pull()


@route("POST", "/api/sync/push")
def _sync_push(request):
    return datasync.push()


@route("POST", "/api/quit")
def _quit(request):
    threading.Thread(target=_quit.server.shutdown, daemon=True).start()
    return {"ok": True, "stopping": True}


# --------------------------------------------------------------------------------- serving
class Handler(BaseHTTPRequestHandler):
    server_version = f"{INFO['slug']}/{version()}"
    protocol_version = "HTTP/1.1"

    def log_message(self, *a):                                 # the launcher's console is the log
        pass

    def send(self, status: int, body: bytes, content_type: str):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def answer(self, method: str):
        self.server.last_seen = time.time()
        path, _, query = self.path.partition("?")
        if path.startswith("/static/"):
            return self.static(os.path.basename(path))
        handler = ROUTES.get((method, path))
        if handler is None:
            return self.send(404, b'{"error":"no such path"}', "application/json")
        length = int(self.headers.get("Content-Length") or 0)
        request = Request(method, path, query, self.rfile.read(length) if length else b"")
        try:
            result = handler(request)
        except Exception as e:                                 # noqa: BLE001  one bad route never stops the app
            return self.send(500, json.dumps({"error": repr(e)}).encode(), "application/json")
        status = 200
        if isinstance(result, tuple):
            status, result = result
        if isinstance(result, Raw):
            return self.send(result.status, result.body, result.content_type)
        return self.send(status, json.dumps(result).encode("utf-8"), "application/json")

    def static(self, name: str):
        full = os.path.join(ROOT, "static", name)
        if not os.path.isfile(full):
            return self.send(404, b'{"error":"no such file"}', "application/json")
        with open(full, "rb") as f:
            body = f.read()
        return self.send(200, body, TYPES.get(os.path.splitext(name)[1], "application/octet-stream"))

    def do_GET(self):                                          # noqa: N802
        self.answer("GET")

    def do_HEAD(self):                                         # noqa: N802
        self.answer("GET")

    def do_POST(self):                                         # noqa: N802
        self.answer("POST")

    def do_PUT(self):                                          # noqa: N802
        self.answer("PUT")

    def do_DELETE(self):                                       # noqa: N802
        self.answer("DELETE")


def watchdog(server) -> None:
    """Stop once the page has gone quiet. This is the whole reason closing a window pushes the data."""
    while IDLE > 0:
        time.sleep(2)
        if time.time() - server.last_seen > IDLE:
            threading.Thread(target=server.shutdown, daemon=True).start()
            return


def make_server(on_port: int | None = None) -> ThreadingHTTPServer:
    """The server, not yet running. The iOS launcher needs this handle: Pythonista has no subprocesses, so
    the app runs inside the launcher's own process and is stopped from there."""
    os.makedirs(DATA, exist_ok=True)
    register()
    server = ThreadingHTTPServer(("127.0.0.1", on_port or port()), Handler)
    server.daemon_threads = True
    server.last_seen = time.time()
    _quit.server = server
    threading.Thread(target=watchdog, args=(server,), daemon=True).start()
    return server


def main() -> int:
    server = make_server()
    print(f"{INFO['name']} {version()} on http://127.0.0.1:{server.server_address[1]}/  (data: {DATA})",
          flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0
